language: r
cache: packages

matrix:
  include:
    - os: linux
      r: 3.2
    - os: linux
      r: 3.3
    - os: linux
      r: 3.4
    - os: linux
      r: 3.5
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew install libxml2
        - brew link --force libxml2

addons:
  apt:
    packages:
      - libxml2-dev
